---
title: "EDA Summary"
author: "Yanni Lan"
date: "3/17/2020"
output: html_document
---
### Exploratory dataset analysis 
## We will use the train dataset inspect the data 
# load the library
```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(skimr)
library(ggplot2)
library(corrplot)
library(RColorBrewer)
```

##read datasets
```{r}
train_data <- read.csv("~/BA_888/train_data.csv")
Worth_to_buy <- train_data %>% filter(train_data$Class== 1)
Not_Worth_to_buy <- train_data %>% filter(train_data$Class== 0)
data <- as.data.frame(rbind(Worth_to_buy,Not_Worth_to_buy))

```


# Distribution by Class (Buy-Worthy or Not Buy-worthy)
```{r}
data %>% 
  ggplot()+
  geom_bar(aes(factor(Class)), fill = "#005b5e")+
  labs(
    title=" Distribution of Buy-worthy and Not Buy-worthy Stocks",
    x = "Class",
    y = "Number of Stocks"
  )
```

## Plot sector distribution
```{r}
data %>% 
  ggplot()+
  geom_bar(aes(factor(Sector)), fill = "#005b5e")+
  labs(
    title="Distribution of different industry sectors of Stocks",
    x = "Sector",
    y = "Number of Stocks"
  )+
  theme(plot.title = element_text(size = 20, hjust = 0.5),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        axis.text.x = element_text(size = 10, angle = 15)
  )
```



